[[Metrics]]
    Period = 5
    Stat = "Sum"

    [Metrics.Metric]
    Namespace = "authApi"
    MetricName = "challengesStarted"

    [[Metrics.Metric.Dimensions]]
    Name = "ServiceName"
    Value = "auth-api-challengePostHandler92AD93BF-UH40AniBZd25"

    [[Metrics.Metric.Dimensions]]
    Name = "ServiceType"
    Value = "AWS::Lambda::Function"
