[[metric]]
Namespace="pricingApi"
MetricName="completedPricing"
Stat="Sum"
Period = 5
StartTime=2021-03-21T09:00:00Z
[metric.dimensions]
ServiceName="pricing-api-generatePricePost3D9C7A9C-UERajJf7MzlI"
ServiceType="AWS::Lambda::Function"

[[metric]]
Namespace="AWS/Lambda"
MetricName="Invocations"
Stat="Sum"
Period=5
StartTime=2021-03-21T09:00:00Z
