name: Build and Release
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

#     - name: Test
#       run: go test -v -cover ./...

    - name: Build Changelog
      id: github_release
      uses: mikepenz/release-changelog-builder-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: ${{steps.github_release.outputs.changelog}}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Linux x86
      run: GOOS="linux" GOARCH="amd64" go build -o cdk/lambda/processor/lambda -ldflags "-s -w" cdk/lambda/processor/main.go && go build -o output/cwexport-linux-x86

    - name: Build Linux arm64
      run: GOOS="linux" GOARCH="arm64" go build -o cdk/lambda/processor/lambda -ldflags "-s -w" cdk/lambda/processor/main.go && go build -o output/cwexport-linux-arm64

    - name: Build MacOS x86
      run: GOOS="darwin" GOARCH="amd64" go build -o cdk/lambda/processor/lambda -ldflags "-s -w" cdk/lambda/processor/main.go && go build -o output/cwexport-darwin-x86

    - name: Build MacOS arm64
      run: GOOS="darwin" GOARCH="arm64" go build -o cdk/lambda/processor/lambda -ldflags "-s -w" cdk/lambda/processor/main.go && go build -o output/cwexport-darwin-arm64

    - name: Build Windows x86
      run: GOOS="windows" GOARCH="amd64" go build -o cdk/lambda/processor/lambda -ldflags "-s -w" cdk/lambda/processor/main.go && go build -o output/cwexport-win-x86

    - name: Upload linux x86 artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./output/cwexport-linux-x86
        asset_name: cwexport-linux-x86
        asset_content_type: application/octet-stream

    - name: Upload linux arm64 artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./output/cwexport-linux-arm64
        asset_name: cwexport-linux-arm64
        asset_content_type: application/octet-stream

    - name: Upload darwin x86 artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./output/cwexport-darwin-x86
        asset_name: cwexport-darwin-x86
        asset_content_type: application/octet-stream

    - name: Upload darwin arm64 artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./output/cwexport-darwin-arm64
        asset_name: cwexport-darwin-arm64
        asset_content_type: application/octet-stream

    - name: upload windows artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./output/cwexport-win-x86
        asset_name: cwexport-win-x86
        asset_content_type: application/octet-stream